name: Build and publish dev release

on:
  push:
    branches: [ main ]

jobs:
  publish-dev-container:
    runs-on: docker
    container:
      image: catthehacker/ubuntu:act-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get commit ID
        id: commit_id
        shell: bash
        run: |
          COMMIT_SHA="${{ github.sha }}"
          echo "::set-output name=short_commit_id::$(echo ${COMMIT_SHA::10})"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: forge.lyratris.com
          username: lrts
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Publish Docker Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            forge.lyratris.com/${{ github.repository }}:dev
          labels: |
            org.opencontainers.image.version=${{ steps.commit_id.outputs.short_commit_id }}
          platforms: linux/amd64,linux/arm64