name: Build and publish release release

on:
  push:
    branches: [ release/v* ]

jobs:
  publish-release-container:
    runs-on: docker
    container:
      image: catthehacker/ubuntu:act-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get cleaned branch name
        id: clean_name
        run: |
          REF_NAME=$(echo "${{ github.ref }}" | sed -e 's/refs\/heads\///' -e 's/refs\/tags\///' -e 's/release\/v//')
          echo "Cleaned name is ${REF_NAME}"
          echo "branch=${REF_NAME}" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: forge.lyratris.com
          username: lrts
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Publish Docker Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            forge.lyratris.com/${{ github.repository }}:latest
            forge.lyratris.com/${{ github.repository }}:${{ steps.clean_name.outputs.branch }}
          labels: |
            org.opencontainers.image.version=${{ steps.clean_name.outputs.branch }}
          platforms: linux/amd64,linux/arm64