#!/bin/bash

if ! id "dyndns-agent" &>/dev/null; then
    # Create the system user
	useradd \
		--create-home \
		--no-create-home \
		--shell /usr/bin/nologin \
		--group daemon \
		--system \
		dyndns-agent
fi

# Install default config file
if [ ! -d "/etc/dyndns-agent" ]; then

	mkdir -p "/etc/dyndns-agent"
	cp /usr/share/dyndns-agent/config.ini /etc/dyndns-agent/config.ini
	
fi

# change permissions
chown -R dyndns-agent:dyndns-agent /etc/dyndns-agent

# Enable the service
systemctl enable lyratris-dnsagent.service

# Explicitly exit 0
exit 0